### ISSUE TITLE
Update proxy to send username to Dashboards, not the user ID

### ISSUE THREAD

**Issue by markdboyd** [cloud-gov/opensearch-dashboards-cf-auth-proxy#104]
When the user logs in via the proxy to OpenSearch Dashboards, in the top right it shows their user ID as the logged-in username. Preferably, it would show their actual user email.

## Acceptance Criteria

- [x] Update the proxy to show user email instead of user ID in Dashboards
- [x] Add e2e test for verifying username appears correctly in dashboard?
- [x] Update the version of the proxy
- [x] Update the blob for the proxy in the opensearch-boshrelease

**Comment by JasonTheMain** [comment]
Closed with pull request https://github.com/cloud-gov/opensearch-dashboards-cf-auth-proxy/pull/117
